name: 15-minute-cron
on:
  schedule:
    - cron: "* * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: "🎉 The CRON job was automatically triggered"
        # run: |
        #   curl --request POST \
        #   --url 'https://yoursite.com/api/cron' \
        #   --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
